version: '3.9'

services:
  smokeping:
    container_name: smokeping
    image: lscr.io/linuxserver/smokeping:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuching
    volumes:
      - /data/smokeping/config:/config
      - /data/smokeping/data:/data
    ports:
      - 83:80
    restart: unless-stopped